db:
  url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
  username: root
  password: root
  driverClassName: com.mysql.cj.jdbc.Driver